---
# Tasks if setting up mofed from rpm repository
  - name: Install Mellanox-Ofed
    block:
    - name: Set kernel version to variable
      set_fact:
        defined_kernel: "{{ mofed_kernel | default('nil') }}"
        running_kernel: "{{ ansible_kernel | default('nil') }}"

    - name: Fail if no kernel is set for play
      fail:
        msg: "Neither mofed_kernel nor ansible_kernel is set."
      when: defined_kernel == 'nil' and running_kernel == 'nil'

    - name: Add needed dnf repository for mofed and lustre
      ansible.builtin.yum_repository:
        name: "{{mofed_repo.name}}"
        description: "{{mofed_repo.description}}"
        baseurl: "{{mofed_repo.baseurl}}"
        gpgcheck: "{{mofed_repo.gpgcheck}}"

    # This will cause issues for indepotensy as names overlap between RHEL-ofed and mofed. 
    # Original idea was to provide upgrade path from RHEL->Mofed. Removing this functionality.
    #- name: Make sure RHEL ib is absent
    #  ansible.builtin.dnf:
    #    name: "{{ item }}"
    #    state: absent
    #    autoremove: yes
    #  loop: "{{ rdma_packages }}"

    - name: Install various packages (defined in variable mofed_packages)
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ mofed_packages }}"
      register: mofed_packages_updated

    - name: Restart openibd service
      command: "/etc/init.d/openibd restart"
      when: mofed_packages_updated.changed and openibd_restart|bool

    - name: Add ib to boot initrd with dracut
      command: "dracut -f --kver {{ defined_kernel | default(running_kernel) }}"
      when: mofed_packages_updated.changed

    when: mofed | default(false)|bool

# Tasks if using RHEL provided mofed
  - name: Install various packages
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop: "{{ rdma_packages }}"
    when: not mofed | default(true)|bool

# these are common tasks after proper version of ofed packages has been installed
  - name: "Comment out not needed RDMA modules"
    replace:
      path: "{{ rdma_config }}"
      regexp: "^{{ item }}"
      replace: "# {{ item }}"
    loop: "{{ rdma_disable_kmod }}"

  - name: Make sure opensm is installed if managed by ansible
    package:
      name: opensm
      state: present
    when: rdma_manage_opensm|bool

  - name: Generate the OpenSM partition configuration file
    template:
      src: partitions.conf.j2
      dest: /etc/rdma/partitions.conf
      owner: root
      mode: 0644
    when: rdma_manage_opensm|bool
    notify: restart opensm

  - name: Set cgoup limits for all users
    ansible.builtin.lineinfile:
      path: /etc/rdma/opensm.conf
      regexp: "^{{ item.key }}"
      line: "{{ item.key }} {{ item.value }}"
    loop: "{{ rdma_opensm_conf | dict2items }}"
    when: rdma_manage_opensm|bool
    notify: restart opensm


  - name: Manage the opensm service
    service:
      name: opensm
      state: "{{ rdma_opensm_state }}"
      enabled: "{{ rdma_opensm_enabled }}"
    when:
      - rdma_manage_opensm|bool
